# image widget that draws an artificial horizon according to the X rotation of a twist message
# uses params["ext_gain"] to select the horizon
# uses params["ext_gain"] to select the craft
# uses params["size"] to scale the image

# uses msg.angular.x to perform rotations

compass_widget_node:
  ros__parameters:
    message_module: "geometry_msgs.msg"
    message_class: "Twist"
    template_params:
      size: 200
      ext_gain: 0.1
      int_gain: -0.9
    template_file: "artificial-horizon.svg.j2"
